"use client";

import React from "react";
import {
  SparkleIcon,
  BrainIcon,
  TrendUpIcon,
  ArrowsClockwise,
} from "@phosphor-icons/react";
import ReactMarkdown from "react-markdown";

interface InsightsProps {
  insights: string | null;
  loading: boolean;
  onGenerate: () => void; // 🔥 Naya prop button click ke liye
}

export default function Insights({
  insights,
  loading,
  onGenerate,
}: InsightsProps) {
  return (
    <div className="space-y-6 p-6 max-w-5xl mx-auto min-h-full flex flex-col">
      {/* --- PAGE HEADER --- */}
      <header className="mb-4 mt-2 flex flex-col sm:flex-row sm:items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-3 text-indigo-400 mb-2">
            <div className="p-2.5 bg-indigo-500/10 rounded-xl border border-indigo-500/20">
              <SparkleIcon size={28} weight="duotone" />
            </div>
            <h1 className="text-3xl font-bold text-white tracking-tight">
              AI Productivity Insights
            </h1>
          </div>
          <p className="text-gray-400 text-sm sm:text-base max-w-2xl mt-2">
            A deep dive into your task history, habits, and workflow
            optimizations generated by your personal AI coach.
          </p>
        </div>

        {/* Agar report pehle se hai, toh refresh button dikhao */}
        {insights && !loading && (
          <button
            onClick={onGenerate}
            className="inline-flex items-center gap-2 bg-gray-800 hover:bg-gray-700 text-gray-300 border border-gray-700 px-4 py-2 rounded-xl text-sm font-medium transition-colors"
          >
            <ArrowsClockwise size={18} weight="bold" />
            Refresh Report
          </button>
        )}
      </header>

      {/* --- MAIN CONTENT CONTAINER --- */}
      <div className="bg-[#111827] border border-gray-800 rounded-3xl overflow-hidden flex-1 shadow-2xl relative flex flex-col">
        {/* Decorative Glowing Orbs in Background */}
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-indigo-600/10 blur-[120px] rounded-full pointer-events-none"></div>
        <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-purple-600/10 blur-[120px] rounded-full pointer-events-none"></div>

        <div className="relative z-10 p-6 sm:p-10 lg:p-14 flex-1 flex flex-col">
          {loading ? (
            // --- LOADING STATE ---
            <div className="flex-1 flex flex-col items-center justify-center py-20">
              <div className="relative flex items-center justify-center mb-6">
                <div className="absolute inset-0 bg-indigo-500/20 blur-xl rounded-full"></div>
                <BrainIcon
                  size={64}
                  weight="duotone"
                  className="text-indigo-400 animate-pulse relative z-10"
                />
              </div>
              <h3 className="text-2xl font-bold text-white mb-3">
                Analyzing Your Workflow...
              </h3>
              <p className="text-gray-400 text-center max-w-md leading-relaxed">
                Our AI is crunching the data from your entire task history to
                find hidden patterns, strengths, and areas for improvement.
              </p>
            </div>
          ) : insights ? (
            // --- SUCCESS STATE (CUSTOM STYLED MARKDOWN) ---
            <div
              className="text-gray-300 text-sm sm:text-base leading-relaxed tracking-wide space-y-4 max-w-3xl mx-auto w-full
                            [&>h1]:text-3xl [&>h1]:font-extrabold [&>h1]:text-white [&>h1]:mb-6 [&>h1]:mt-8
                            [&>h2]:text-2xl [&>h2]:font-bold [&>h2]:text-white [&>h2]:mb-4 [&>h2]:mt-10 [&>h2]:border-b [&>h2]:border-gray-800 [&>h2]:pb-2
                            [&>h3]:text-xl [&>h3]:font-bold [&>h3]:text-indigo-300 [&>h3]:mb-3 [&>h3]:mt-8
                            [&>p]:mb-5 [&>p]:leading-7 [&>p]:text-gray-300
                            [&>ul]:list-disc [&>ul]:pl-6 [&>ul]:mb-6 [&>ul>li]:mb-3 [&>ul>li]:pl-1 [&>ul>li::marker]:text-indigo-500
                            [&>ol]:list-decimal [&>ol]:pl-6 [&>ol]:mb-6 [&>ol>li]:mb-3 [&>ol>li]:pl-1
                            [&>strong]:text-white [&>strong]:font-semibold
                            [&>hr]:border-gray-800 [&>hr]:my-10
                            [&>blockquote]:border-l-4 [&>blockquote]:border-indigo-500 [&>blockquote]:pl-5 [&>blockquote]:py-1 [&>blockquote]:italic [&>blockquote]:text-gray-400 [&>blockquote]:bg-indigo-500/5 [&>blockquote]:rounded-r-lg
                        "
            >
              <ReactMarkdown>{insights}</ReactMarkdown>
            </div>
          ) : (
            // --- INITIAL / EMPTY STATE ---
            <div className="flex-1 flex flex-col items-center justify-center py-20">
              <div className="p-4 bg-gray-800/50 border border-gray-700/50 rounded-2xl mb-6 shadow-lg">
                <TrendUpIcon
                  size={56}
                  className="text-indigo-400"
                  weight="duotone"
                />
              </div>
              <h3 className="text-2xl font-bold text-white mb-3">
                Ready for your Insights?
              </h3>
              <p className="text-gray-400 text-center max-w-md mb-8">
                Generate a personalized productivity report based on your past
                tasks. The AI will provide actionable tips to optimize your
                workflow.
              </p>
              <button
                onClick={onGenerate}
                className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white px-8 py-3.5 rounded-xl font-bold transition-all shadow-lg shadow-indigo-900/50 active:scale-95"
              >
                <SparkleIcon size={20} weight="fill" />
                Generate AI Report
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
